# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cff60109790e8a69c6b1a366045d9aa50cc75238352c402b9210b1d14146fa71fa803394e3f4e81fd0fddbbbbbb0278b0b0de8ef98b040391a3558970af7aec

test:
  secret_key_base: 5a146bbdcb8f1c2ad211687bf5d1d89b9b2bd04e23f40b1e44d7b73a020687f5f4c13ca445dce0174b24a7d2a5d1cf56ff936f71da8c556f750a6202fe64927e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
